/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adrian.rey.brea.test_conducir;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author adrir
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    private boolean oscuro;
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        oscuro = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elegirBBDD = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        testOnline = new javax.swing.JButton();
        modoOscuro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        elegirBBDD.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        elegirBBDD.setText("Elegir");
        elegirBBDD.setMaximumSize(new java.awt.Dimension(85, 60));
        elegirBBDD.setMinimumSize(new java.awt.Dimension(85, 60));
        try{
            URL url = new URL("https://www.dropbox.com/s/evle7hxuw5br9cw/play.png?raw=1");
            Image img = ImageIO.read(url);
            elegirBBDD.setIcon(new ImageIcon(img));
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        elegirBBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirBBDDActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        try{
            URL url = new URL("https://www.dropbox.com/s/iyegq1j56pdiio7/exit.png?raw=1");
            Image img = ImageIO.read(url);
            salir.setIcon(new ImageIcon(img));
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        testOnline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        testOnline.setText("Test Online");
        testOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testOnlineActionPerformed(evt);
            }
        });

        modoOscuro.putClientProperty("JButton.buttonType", "roundRect");
        modoOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoOscuroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(salir)
                            .addComponent(elegirBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 194, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(testOnline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modoOscuro)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {elegirBBDD, salir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testOnline)
                    .addComponent(modoOscuro))
                .addGap(110, 110, 110)
                .addComponent(elegirBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        try{
            URL url = new URL("https://www.dropbox.com/s/aywzylrqwn9a2nd/moon.png?raw=1");
            Image img = ImageIO.read(url);
            modoOscuro.setIcon(new ImageIcon(img));
        }
        catch(Exception ex){
            ex.printStackTrace();
            modoOscuro.setText("Modo oscuro");
        }

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void elegirBBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirBBDDActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            fc.setFileFilter(new FileNameExtensionFilter("Test de conducir *.tdc", "tdc"));
            int returnVal = fc.showOpenDialog(PantallaPrincipal.this);
            
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                lanzarTest(file, false);
            }
        } catch (HeadlessException ex) {
            System.out.println("Revisa la conexion a internet");
        } 
          
    }//GEN-LAST:event_elegirBBDDActionPerformed

    private void testOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testOnlineActionPerformed
        File fil = null;
        lanzarTest(fil, true);
    }//GEN-LAST:event_testOnlineActionPerformed
    public void modoOscuro(){
        oscuro = !oscuro;
        try {
            if(oscuro){
                UIManager.setLookAndFeel(new com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme());
            }
            else{
                UIManager.setLookAndFeel(new com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme());
            }
            SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void modoOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoOscuroActionPerformed
        modoOscuro();
    }//GEN-LAST:event_modoOscuroActionPerformed
    public void lanzarTest(File file, boolean online){
        JFrame.setDefaultLookAndFeelDecorated(true);
        PantallaTest test = new PantallaTest(file, online);
        test.setVisible(true);
        this.dispose();
        
    }
    public PantallaPrincipal(JButton elegirBBDD, JButton salir, JButton testOnline) throws HeadlessException {
        this.elegirBBDD = elegirBBDD;
        this.salir = salir;
        this.testOnline = testOnline;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaPrincipal pantallaPrincipal = new PantallaPrincipal();
                pantallaPrincipal.setVisible(true);
                pantallaPrincipal.modoOscuro();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton elegirBBDD;
    private javax.swing.JButton modoOscuro;
    private javax.swing.JButton salir;
    private javax.swing.JButton testOnline;
    // End of variables declaration//GEN-END:variables
}
