/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adrian.rey.brea.test_conducir;

import java.util.ArrayList;

/**
 *
 * @author adrir
 */
public class PantallaResultados extends javax.swing.JFrame {
    ArrayList<Pregunta> preguntas;
    /**
     * Creates new form PantallaResultados
     * @param preguntas
     */
    public PantallaResultados(ArrayList<Pregunta> preguntas) {
        this.setTitle("RESULTADOS");
        this.preguntas = preguntas;
        initComponents();
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        int acertadas = 0;
        for(int i = 0; i < preguntas.size(); i++){
            jTabbedPane1.add("Pregunta " + (i + 1),new PreguntaRespondida(preguntas.get(i)));
            switch(preguntas.get(i).getRespuestaMarcada()){
                case 1:
                    if(preguntas.get(i).getR1().isCorrecta())
                        acertadas++;
                    break;
                case 2:
                    if(preguntas.get(i).getR2().isCorrecta())
                        acertadas++;
                    break;
                case 3:
                    if(preguntas.get(i).getR3().isCorrecta())
                        acertadas++;
                    break;
                case 4:
                    if(preguntas.get(i).getR4().isCorrecta())
                        acertadas++;
                    break;
            }
        }
        
        if(acertadas >= preguntas.size() - (preguntas.size() / 10))
            acertadasLabel.setText(acertadas + "/" + preguntas.size() +  " APROBADO");
        else
            acertadasLabel.setText(acertadas + "/" + preguntas.size() +  " SUSPENSO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        respuestas = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        salir = new javax.swing.JButton();
        acertadasLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        respuestas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        respuestas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        respuestas.setText("Respuestas");

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        salir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salir.setText("---Salir del programa---");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        acertadasLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        acertadasLabel.setText("99/99 APROBADO");
        acertadasLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(respuestas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(salir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 522, Short.MAX_VALUE)
                        .addComponent(acertadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(respuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acertadasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acertadasLabel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel respuestas;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
