/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adrian.rey.brea.test_conducir;

import java.awt.HeadlessException;
import java.io.*;
import java.time.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTabbedPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author adrir
 */
public class PantallaResultados extends javax.swing.JFrame {
    ArrayList<Pregunta> preguntas;
    ArrayList<Pregunta> preguntasTestActual;
    String fichero;
    /**
     * Creates new form PantallaResultados
     * @param preguntas
     * @param fichero
     */
    public PantallaResultados(ArrayList<Pregunta> preguntas, String fichero) {
        LocalDateTime actual = LocalDateTime.now();
        this.fichero = fichero + "-" + actual.getHour()  + actual.getMinute() + actual.getSecond() + actual.getDayOfMonth()+ actual.getMonthValue() + actual.getYear() +".fdt" ;
        this.setTitle("Resultados");
        this.preguntas = preguntas;
        preguntasTestActual = preguntas;
        initComponents();
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        generarPanel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        respuestas = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        salir = new javax.swing.JButton();
        acertadasLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        guardarTest = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        respuestas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        respuestas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        respuestas.setText("Respuestas");

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        salir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salir.setText("---Salir del programa---");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        acertadasLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        acertadasLabel.setText("99/99 APROBADO");
        acertadasLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        menuOpciones.setText("Opciones");

        abrir.setText("Abrir...");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        menuOpciones.add(abrir);
        menuOpciones.add(jSeparator2);

        guardarTest.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        guardarTest.setText("Guardar");
        guardarTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTestActionPerformed(evt);
            }
        });
        menuOpciones.add(guardarTest);
        menuOpciones.add(jSeparator1);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuOpciones.add(menuSalir);

        jMenuBar1.add(menuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(respuestas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(salir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 522, Short.MAX_VALUE)
                        .addComponent(acertadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(respuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acertadasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void generarPanel() {
        int acertadas = 0;
        jTabbedPane1.removeAll();
        for(int i = 0; i < preguntas.size(); i++){
            jTabbedPane1.add("Pregunta " + (i + 1),new PreguntaRespondida(preguntas.get(i)));
            switch(preguntas.get(i).getRespuestaMarcada()){
                case 1:
                    if(preguntas.get(i).getR1().isCorrecta())
                        acertadas++;
                    break;
                case 2:
                    if(preguntas.get(i).getR2().isCorrecta())
                        acertadas++;
                    break;
                case 3:
                    if(preguntas.get(i).getR3().isCorrecta())
                        acertadas++;
                    break;
                case 4:
                    if(preguntas.get(i).getR4().isCorrecta())
                        acertadas++;
                    break;
            }
        }
        
        if(acertadas >= preguntas.size() - (preguntas.size() / 10))
            acertadasLabel.setText(acertadas + "/" + preguntas.size() +  " APROBADO");
        else
            acertadasLabel.setText(acertadas + "/" + preguntas.size() +  " SUSPENSO");
    }
    
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void guardarTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTestActionPerformed
        ObjectOutputStream oos = null;
        try {
            File file = new File(fichero);
            oos = new ObjectOutputStream(new FileOutputStream(file));
            System.out.println(fichero);
            for(Pregunta pregunta : preguntasTestActual)
                oos.writeObject(pregunta);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PantallaResultados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PantallaResultados.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                oos.close();
            } catch (IOException ex) {
                Logger.getLogger(PantallaResultados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_guardarTestActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            fc.setFileFilter(new FileNameExtensionFilter("Fin de test *.fdt", "fdt"));
            int returnVal = fc.showOpenDialog(PantallaResultados.this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file));
                preguntas = new ArrayList<>();
                Pregunta pregunta;
                try{
                    while((pregunta = (Pregunta)ois.readObject()) != null)
                        preguntas.add(pregunta);
                }
                catch(java.io.EOFException ex){
                }
                ois.close();
                generarPanel();
            }
        } catch (HeadlessException ex) {
            System.out.println("Revisa la conexion a internet");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PantallaResultados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PantallaResultados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaResultados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abrirActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JLabel acertadasLabel;
    private javax.swing.JMenuItem guardarTest;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JLabel respuestas;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

    
}
