/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adrian.rey.brea.test_conducir;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author adrir
 */
public class PreguntaRespondida extends javax.swing.JPanel {

    /**
     * Creates new form PreguntaRespondida
     * @param pregunta
     */
    public PreguntaRespondida(Pregunta pregunta) {
        initComponents();
        try{
            URL url = new URL(pregunta.getEnlaceImg());
            Image img = java.awt.Toolkit.getDefaultToolkit().createImage(url);
            Image preguntaImg = img.getScaledInstance(145, 100, Image.SCALE_SMOOTH);
            imagenLabel.setIcon(new ImageIcon(preguntaImg));
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        
        
       
        preguntaLabel.setText("<html>" + pregunta.getPregunta() + "</html>");
        switch(pregunta.getRespuestaMarcada()){
            case 1:
                respuestaSeleccionada1.setText("<html> Respuesta seleccionada: " + pregunta.getR1().getRespuesta() + "</html>");
                break;
            case 2:
                respuestaSeleccionada1.setText("<html> Respuesta seleccionada: " + pregunta.getR2().getRespuesta() + "</html>");
                break;
            case 3:
                respuestaSeleccionada1.setText("<html> Respuesta seleccionada: " + pregunta.getR3().getRespuesta() + "</html>");
                break;
            case 4:
                respuestaSeleccionada1.setText("<html> Respuesta seleccionada: " + pregunta.getR4().getRespuesta() + "</html>");
                break;
            default:
                respuestaSeleccionada1.setText("<html> Respuesta seleccionada: Ninguna seleccionada </html>");
                break;
        }
        if(pregunta.getR1().isCorrecta())
            respuestaCorrecta.setText("<html> Respuesta correcta: " + pregunta.getR1().getRespuesta() + "</html>");
        else if(pregunta.getR2().isCorrecta())
            respuestaCorrecta.setText("<html> Respuesta correcta: " + pregunta.getR2().getRespuesta() + "</html>");
        else if(pregunta.getR3().isCorrecta())
            respuestaCorrecta.setText("<html> Respuesta correcta: " + pregunta.getR3().getRespuesta() + "</html>");
        else if(pregunta.getR4().isCorrecta())
            respuestaCorrecta.setText("<html> Respuesta correcta: " + pregunta.getR4().getRespuesta() + "</html>");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preguntaLabel = new javax.swing.JLabel();
        respuestaCorrecta = new javax.swing.JLabel();
        respuestaSeleccionada1 = new javax.swing.JLabel();
        imagenLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(940, 433));

        preguntaLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        preguntaLabel.setText("Pregunta");

        respuestaCorrecta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        respuestaCorrecta.setText("Pregunta correcta");

        respuestaSeleccionada1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        respuestaSeleccionada1.setText("Pregunta seleccionada");

        imagenLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        imagenLabel.setMinimumSize(new java.awt.Dimension(100, 100));
        imagenLabel.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(respuestaSeleccionada1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuestaCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(preguntaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(respuestaSeleccionada1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(respuestaCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel preguntaLabel;
    private javax.swing.JLabel respuestaCorrecta;
    private javax.swing.JLabel respuestaSeleccionada1;
    // End of variables declaration//GEN-END:variables
}
