/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adrian.rey.brea.test_conducir;

import javax.swing.ImageIcon;

/**
 *
 * @author adrir
 */
public class PreguntaRespondida extends javax.swing.JPanel {

    /**
     * Creates new form PreguntaRespondida
     * @param pregunta
     */
    public PreguntaRespondida(Pregunta pregunta) {
        initComponents();
        imagenLabel.setIcon(new ImageIcon(pregunta.getImg()));
        preguntaLabel.setText("<html>" + pregunta.getPregunta() + "</html>");
        switch(pregunta.getRespuestaMarcada()){
            case 1:
                respuestaSeleccionada1.setText("<html> Respuesta seleccionada: " + pregunta.getR1().getRespuesta() + "</html>");
                break;
            case 2:
                respuestaSeleccionada1.setText("<html> Respuesta seleccionada: " + pregunta.getR2().getRespuesta() + "</html>");
                break;
            case 3:
                respuestaSeleccionada1.setText("<html> Respuesta seleccionada: " + pregunta.getR3().getRespuesta() + "</html>");
                break;
            case 4:
                respuestaSeleccionada1.setText("<html> Respuesta seleccionada: " + pregunta.getR4().getRespuesta() + "</html>");
                break;
            default:
                respuestaSeleccionada1.setText("<html> Respuesta seleccionada: Ninguna seleccionada </html>");
                break;
        }
        if(pregunta.getR1().isCorrecta())
            respuestaCorrecta.setText("<html> Respuesta correcta: " + pregunta.getR1().getRespuesta() + "</html>");
        else if(pregunta.getR2().isCorrecta())
            respuestaCorrecta.setText("<html> Respuesta correcta: " + pregunta.getR2().getRespuesta() + "</html>");
        else if(pregunta.getR3().isCorrecta())
            respuestaCorrecta.setText("<html> Respuesta correcta: " + pregunta.getR3().getRespuesta() + "</html>");
        else if(pregunta.getR4().isCorrecta())
            respuestaCorrecta.setText("<html> Respuesta correcta: " + pregunta.getR4().getRespuesta() + "</html>");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preguntaLabel = new javax.swing.JLabel();
        respuestaCorrecta = new javax.swing.JLabel();
        respuestaSeleccionada1 = new javax.swing.JLabel();
        imagenLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(940, 433));

        preguntaLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        preguntaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preguntaLabel.setText("Pregunta");

        respuestaCorrecta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        respuestaCorrecta.setText("Pregunta correcta");

        respuestaSeleccionada1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        respuestaSeleccionada1.setText("Pregunta seleccionada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(respuestaCorrecta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(respuestaSeleccionada1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(respuestaCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(respuestaSeleccionada1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(213, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel preguntaLabel;
    private javax.swing.JLabel respuestaCorrecta;
    private javax.swing.JLabel respuestaSeleccionada1;
    // End of variables declaration//GEN-END:variables
}
